global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
  - job_name: 'app'
    scrape_interval: 5s
    scheme: https
    basic_auth:
      username: admin
      password: admin
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ln-pos-server:9443']